"""Markdown briefing generator."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from jinja2 import Template

from .config import PROJECT_ROOT, get_config
from .models import BriefingMeta, ScoredSignal

BRIEFING_TEMPLATE = Template("""\
# AI Intelligence Radar — {{ date }}

> Generated: {{ generated_at }} | Signals: {{ total_collected }} collected → {{ total_extracted }} extracted → {{ total_clusters }} clusters → {{ signals_in_briefing }} selected
{% if topics %}
> **Topics**: {{ topics | join(', ') }}
{% endif %}
---
{% for lane_key, lane_label, signals in lanes %}
## {{ lane_label }}
{% for s in signals %}
### {{ loop.index }}. {{ s.signal.title }}

{{ s.signal.summary }}

- **Source**: {{ s.signal.raw.source if s.signal.raw else 'unknown' }} | [Link]({{ s.signal.raw.url if s.signal.raw else '#' }})
- **Score**: {{ "%.2f"|format(s.composite_score) }} (novelty={{ "%.2f"|format(s.novelty_score) }}, impact={{ "%.2f"|format(s.impact_score) }}, relevance={{ "%.2f"|format(s.relevance_score) }}, authority={{ "%.2f"|format(s.authority_score) }})
{%- if s.signal.entities %}
- **Entities**: {{ s.signal.entities | join(', ') }}
{%- endif %}

{% endfor %}
{% endfor %}
---

*Generated by [AI Intelligence Radar](https://github.com/news-radar)*
""")


def generate_briefing(
    date: str,
    selected: list[ScoredSignal],
    stats: dict,
    topics: list[str] | None = None,
) -> BriefingMeta:
    """Generate a markdown briefing file and return metadata."""
    cfg = get_config()
    lanes_cfg = cfg.get("lanes", {})
    briefings_dir = PROJECT_ROOT / cfg.get("briefings_dir", "briefings")
    briefings_dir.mkdir(parents=True, exist_ok=True)

    # Group by lane
    by_lane: dict[str, list[ScoredSignal]] = {}
    for s in selected:
        by_lane.setdefault(s.lane, []).append(s)

    # Build ordered lanes
    lanes = []
    for lane_key, lane_cfg in lanes_cfg.items():
        lane_signals = by_lane.get(lane_key, [])
        if lane_signals:
            lanes.append((lane_key, lane_cfg.get("label", lane_key), lane_signals))

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    content = BRIEFING_TEMPLATE.render(
        date=date,
        generated_at=generated_at,
        total_collected=stats.get("total_collected", 0),
        total_extracted=stats.get("total_extracted", 0),
        total_clusters=stats.get("total_clusters", 0),
        signals_in_briefing=len(selected),
        lanes=lanes,
        topics=topics or [],
    )

    file_path = briefings_dir / f"{date}.md"
    file_path.write_text(content)

    return BriefingMeta(
        date=date,
        generated_at=datetime.now(),
        total_collected=stats.get("total_collected", 0),
        total_extracted=stats.get("total_extracted", 0),
        total_clusters=stats.get("total_clusters", 0),
        signals_in_briefing=len(selected),
        file_path=str(file_path),
        topics=topics or [],
    )
